In [1]:
import pandas as pd
import numpy as np

In [16]:
df = pd.read_csv(r"student_daily_data.csv")
df

   Day  Study_Hours  Sleep_Hours
0  Mon            2            7
1  Tue            3            6
2  Wed            4            6
3  Thu            3            7
4  Fri            5            5
5  Sat            6            8
6  Sun            4            7

In [2]:
c=pd.Series([1,2,3,4,56,7,8,865])
print(c)

0      1
1      2
2      3
3      4
4     56
5      7
6      8
7    865
dtype: int64

In [6]:
c=pd.Series([1,2,3,4,56,7,8,865],index=["A","B","C","D","E","F","G","H"])
print(c)

A      1
B      2
C      3
D      4
E     56
F      7
G      8
H    865
dtype: int64

In [7]:
c=pd.Series([1,2,3,4,56,7,8,865],index=["A","B","C","D","E","F","G","H"])
print(len(c))

8

In [9]:
c=pd.Series({"A":1,"B":2,"C":3,"D":4,"E":56,"F":7,"G":8,"H":865})
print(c)

A      1
B      2
C      3
D      4
E     56
F      7
G      8
H    865
dtype: int64

In [11]:
values=pd.Series([1,2,3,4,5,6,7,8,9])
values.describe()

count    9.000000
mean     5.000000
std      2.738613
min      1.000000
25%      3.000000
50%      5.000000
75%      7.000000
max      9.000000
dtype: float64

In [70]:
print(values.mean())

5.0

In [15]:
print(values.std())

2.7386127875258306

In [16]:
print(values.max())

9

In [17]:
print(values.count())

9

In [19]:
print(values.sum())

45

In [22]:
print(values.mean())

5.0

In [23]:
values.info()

<class 'pandas.core.series.Series'>
RangeIndex: 9 entries, 0 to 8
Series name: None
Non-Null Count  Dtype
--------------  -----
9 non-null      int64
dtypes: int64(1)
memory usage: 204.0 bytes

In [25]:
r1=values.map(lambda x: (x*2)+1)
print(r1)

0     3
1     5
2     7
3     9
4    11
5    13
6    15
7    17
8    19
dtype: int64

In [26]:
r1=values.map(lambda x: x*2)
print(r1)

0     2
1     4
2     6
3     8
4    10
5    12
6    14
7    16
8    18
dtype: int64

In [27]:
r1=values.map(lambda x: (x%2)+1)
print(r1)

0    2
1    1
2    2
3    1
4    2
5    1
6    2
7    1
8    2
dtype: int64

In [28]:
r1=values.map(lambda x: (x%2))
print(r1)

0    1
1    0
2    1
3    0
4    1
5    0
6    1
7    0
8    1
dtype: int64

In [29]:
s = pd.Series([80, 40, 90])

result = s.map(lambda x: "Pass" if x > 50 else "Fail")
print(result)

0    Pass
1    Fail
2    Pass
dtype: object

In [31]:
k=pd.Series([23,34,4556,789])

In [32]:
j=k.apply(lambda x: x+2)
print(j)

0      25
1      36
2    4558
3     791
dtype: int64

In [34]:
value=pd.Series([12,34,24,544,67])
v=value.apply(lambda x: "Pass" if x>30 else "Fail")
print(v)

0    Fail
1    Pass
2    Fail
3    Pass
4    Pass
dtype: object

In [36]:
value1=pd.Series([34,24,544,67,1,223,4,98,54])
value1.sort_values()

4      1
6      4
1     24
0     34
8     54
3     67
7     98
5    223
2    544
dtype: int64

In [38]:
s=pd.Series([30,40,60,10,43,11])
s.sort_values()

3    10
5    11
0    30
1    40
4    43
2    60
dtype: int64

In [39]:
s1=pd.Series([12,54,97,56,43,989])
s1.sort_values(ascending=False)

5    989
2     97
3     56
1     54
4     43
0     12
dtype: int64

In [49]:
d1=s1.drop(1)
print(d1)

0     12
2     97
3     56
4     43
5    989
dtype: int64

In [50]:
d2=s1.drop(3)
print(d2)

0     12
1     54
2     97
4     43
5    989
dtype: int64

In [56]:

a1=pd.Series([1,3,2,4,None,5,67,93,None,9,32,123,None])
a1.isnull()

0     False
1     False
2     False
3     False
4      True
5     False
6     False
7     False
8      True
9     False
10    False
11    False
12     True
dtype: bool

In [60]:
p= pd.Series([2,4,67,None,54,76,6])
p.isnull()

0    False
1    False
2    False
3     True
4    False
5    False
6    False
dtype: bool

In [58]:
p= pd.Series([2,4,67,None,54,76,6])
p.notnull()

0     True
1     True
2     True
3    False
4     True
5     True
6     True
dtype: bool

In [61]:
p= pd.Series([2,4,67,None,54,76,6])
p.notnull().sum()

np.int64(6)

In [62]:
p= pd.Series([2,4,67,None,54,76,6])
p.isnull().sum()

np.int64(1)

In [63]:
a1=pd.Series([1,3,2,4,None,5,67,93,None,9,32,123,None])
a1.isnull().sum()

np.int64(3)

In [64]:
s=pd.Series([1,2,34,None,56,78,98])
s.fillna(88)

0     1.0
1     2.0
2    34.0
3    88.0
4    56.0
5    78.0
6    98.0
dtype: float64

In [66]:
s1=pd.Series([23,34,33,22,45,None,11,None,865,65])
s1.fillna(99)

0     23.0
1     34.0
2     33.0
3     22.0
4     45.0
5     99.0
6     11.0
7     99.0
8    865.0
9     65.0
dtype: float64

values=pd.Series([1,3,5,6,7,8])

In [67]:
values=pd.Series([1,3,5,7,9])
print(values.cumsum())

0     1
1     4
2     9
3    16
4    25
dtype: int64

In [69]:
values=pd.Series([1,3,5,None,7,9,None])
print(values.cumsum())

0     1.0
1     4.0
2     9.0
3     NaN
4    16.0
5    25.0
6     NaN
dtype: float64

In [74]:
p=pd.Series([1,2,3,4,5,6,78,9])
p[p>4]

4     5
5     6
6    78
7     9
dtype: int64

In [75]:
j=pd.Series([12,34,5,6,89,54,324,574,3543,987654])
j[j>100]

6       324
7       574
8      3543
9    987654
dtype: int64

In [78]:
#Dataframes
data={"NAMES" :["AMMU","VARUN","KARTHIK","AKHIL","VAMSHI","VIGNESH","VARMA","HARISH","GUNDU","BABU"],
        "LOCATION":["UPPAL","WARANGAL","VR NAGAR","VS NAGAR","VASAVI NAGAR","PARGATI NAGAR","SURAT","JAGITAL","KARIMNAGAR","ONGOLE"],
        "CODE":[123,34,45,23,4,89,65,432,789,64]}
DETAILS=pd.DataFrame(data)
print(DETAILS)

     NAMES       LOCATION  CODE
0     AMMU          UPPAL   123
1    VARUN       WARANGAL    34
2  KARTHIK       VR NAGAR    45
3    AKHIL       VS NAGAR    23
4   VAMSHI   VASAVI NAGAR     4
5  VIGNESH  PARGATI NAGAR    89
6    VARMA          SURAT    65
7   HARISH        JAGITAL   432
8    GUNDU     KARIMNAGAR   789
9     BABU         ONGOLE    64

In [79]:
DETAILS.head(6)

     NAMES       LOCATION  CODE
0     AMMU          UPPAL   123
1    VARUN       WARANGAL    34
2  KARTHIK       VR NAGAR    45
3    AKHIL       VS NAGAR    23
4   VAMSHI   VASAVI NAGAR     4
5  VIGNESH  PARGATI NAGAR    89

In [80]:
DETAILS.head()

     NAMES      LOCATION  CODE
0     AMMU         UPPAL   123
1    VARUN      WARANGAL    34
2  KARTHIK      VR NAGAR    45
3    AKHIL      VS NAGAR    23
4   VAMSHI  VASAVI NAGAR     4

In [81]:
DETAILS.head(9)

     NAMES       LOCATION  CODE
0     AMMU          UPPAL   123
1    VARUN       WARANGAL    34
2  KARTHIK       VR NAGAR    45
3    AKHIL       VS NAGAR    23
4   VAMSHI   VASAVI NAGAR     4
5  VIGNESH  PARGATI NAGAR    89
6    VARMA          SURAT    65
7   HARISH        JAGITAL   432
8    GUNDU     KARIMNAGAR   789

In [82]:
DETAILS.head(10)

     NAMES       LOCATION  CODE
0     AMMU          UPPAL   123
1    VARUN       WARANGAL    34
2  KARTHIK       VR NAGAR    45
3    AKHIL       VS NAGAR    23
4   VAMSHI   VASAVI NAGAR     4
5  VIGNESH  PARGATI NAGAR    89
6    VARMA          SURAT    65
7   HARISH        JAGITAL   432
8    GUNDU     KARIMNAGAR   789
9     BABU         ONGOLE    64

In [83]:
DETAILS.describe()

             CODE
count   10.000000
mean   166.800000
std    250.780914
min      4.000000
25%     36.750000
50%     64.500000
75%    114.500000
max    789.000000

In [84]:
DETAILS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   NAMES     10 non-null     object
 1   LOCATION  10 non-null     object
 2   CODE      10 non-null     int64
dtypes: int64(1), object(2)
memory usage: 372.0+ bytes

In [85]:
DETAILS.tail()

     NAMES       LOCATION  CODE
5  VIGNESH  PARGATI NAGAR    89
6    VARMA          SURAT    65
7   HARISH        JAGITAL   432
8    GUNDU     KARIMNAGAR   789
9     BABU         ONGOLE    64

In [86]:
DETAILS.tail(8)

     NAMES       LOCATION  CODE
2  KARTHIK       VR NAGAR    45
3    AKHIL       VS NAGAR    23
4   VAMSHI   VASAVI NAGAR     4
5  VIGNESH  PARGATI NAGAR    89
6    VARMA          SURAT    65
7   HARISH        JAGITAL   432
8    GUNDU     KARIMNAGAR   789
9     BABU         ONGOLE    64

In [88]:
DETAILS.tail(10)

     NAMES       LOCATION  CODE
0     AMMU          UPPAL   123
1    VARUN       WARANGAL    34
2  KARTHIK       VR NAGAR    45
3    AKHIL       VS NAGAR    23
4   VAMSHI   VASAVI NAGAR     4
5  VIGNESH  PARGATI NAGAR    89
6    VARMA          SURAT    65
7   HARISH        JAGITAL   432
8    GUNDU     KARIMNAGAR   789
9     BABU         ONGOLE    64

In [102]:
contact_data = pd.DataFrame ({
'Name': ['Dodagatta Nihar', 'Vignesh', 'Maheshwar', 'Naman', 'Naveen', 'Shreya'],
'Phone Number': ['111-111-1111', '222-222-2222', '333-333-3333', '444-444-4444',
'555-555-5555', '666-666-6666'],
'Email': ['nihar@masscoders.tech', 'vignesh@masscoders.tech', 'maheshwar@massco',
'naveen@masscoders.tech', 'shreya@masscoders.tech', 'varsha@masscoder']
})
print(contact_data)

              Name  Phone Number                    Email
0  Dodagatta Nihar  111-111-1111    nihar@masscoders.tech
1          Vignesh  222-222-2222  vignesh@masscoders.tech
2        Maheshwar  333-333-3333         maheshwar@massco
3            Naman  444-444-4444   naveen@masscoders.tech
4           Naveen  555-555-5555   shreya@masscoders.tech
5           Shreya  666-666-6666         varsha@masscoder

In [103]:
contact_data.head(4)

              Name  Phone Number                    Email
0  Dodagatta Nihar  111-111-1111    nihar@masscoders.tech
1          Vignesh  222-222-2222  vignesh@masscoders.tech
2        Maheshwar  333-333-3333         maheshwar@massco
3            Naman  444-444-4444   naveen@masscoders.tech

In [104]:

contact_data.tail(4)

        Name  Phone Number                   Email
2  Maheshwar  333-333-3333        maheshwar@massco
3      Naman  444-444-4444  naveen@masscoders.tech
4     Naveen  555-555-5555  shreya@masscoders.tech
5     Shreya  666-666-6666        varsha@masscoder

In [106]:
contact_data[::-1]

              Name  Phone Number                    Email
5           Shreya  666-666-6666         varsha@masscoder
4           Naveen  555-555-5555   shreya@masscoders.tech
3            Naman  444-444-4444   naveen@masscoders.tech
2        Maheshwar  333-333-3333         maheshwar@massco
1          Vignesh  222-222-2222  vignesh@masscoders.tech
0  Dodagatta Nihar  111-111-1111    nihar@masscoders.tech

In [108]:
data={"NAMES" :["AMMU","VARUN","KARTHIK","AKHIL","VAMSHI","VIGNESH","VARMA","HARISH","GUNDU","BABU"],
        "LOCATION":["UPPAL","WARANGAL","VR NAGAR","VS NAGAR","VASAVI NAGAR","PARGATI NAGAR","SURAT","JAGITAL","KARIMNAGAR","ONGOLE"],
        "CODE":[123,34,45,23,4,89,65,432,789,64]}
DETAILS1=pd.DataFrame(data)
DETAILS1

     NAMES       LOCATION  CODE
0     AMMU          UPPAL   123
1    VARUN       WARANGAL    34
2  KARTHIK       VR NAGAR    45
3    AKHIL       VS NAGAR    23
4   VAMSHI   VASAVI NAGAR     4
5  VIGNESH  PARGATI NAGAR    89
6    VARMA          SURAT    65
7   HARISH        JAGITAL   432
8    GUNDU     KARIMNAGAR   789
9     BABU         ONGOLE    64

In [115]:
# Team roles data
roles_data = {
    'NAMES': ["AMMU","VARUN","KARTHIK","AKHIL","VAMSHI","VIGNESH","VARMA","HARISH","GUNDU","BABU"],
    'Role': ['Founder', 'Growth Manager', 'Community Manager', 'Community Manager',
             'Course Designer', 'Course Designer', 'Public Relations Manager', 'Course Designer', 'Course Designer', 'Public Relations Manager']
}
roles_df = pd.DataFrame(roles_data)
roles_df

     NAMES                      Role
0     AMMU                   Founder
1    VARUN            Growth Manager
2  KARTHIK         Community Manager
3    AKHIL         Community Manager
4   VAMSHI           Course Designer
5  VIGNESH           Course Designer
6    VARMA  Public Relations Manager
7   HARISH           Course Designer
8    GUNDU           Course Designer
9     BABU  Public Relations Manager

In [117]:
merge_df = pd.merge(DETAILS1, roles_df, on='NAMES')
merge_df

     NAMES       LOCATION  CODE                      Role
0     AMMU          UPPAL   123                   Founder
1    VARUN       WARANGAL    34            Growth Manager
2  KARTHIK       VR NAGAR    45         Community Manager
3    AKHIL       VS NAGAR    23         Community Manager
4   VAMSHI   VASAVI NAGAR     4           Course Designer
5  VIGNESH  PARGATI NAGAR    89           Course Designer
6    VARMA          SURAT    65  Public Relations Manager
7   HARISH        JAGITAL   432           Course Designer
8    GUNDU     KARIMNAGAR   789           Course Designer
9     BABU         ONGOLE    64  Public Relations Manager

In [120]:
DETAILS2=pd.DataFrame({ 'NAMES': ["AMMU","VARUN","KARTHIK","AKHIL","VAMSHI","VIGNESH","VARMA","HARISH","GUNDU","BABU"],
                        "RANK":[1,2,3,4,5,6,7,8,9,10]})
DETAILS2

     NAMES  RANK
0     AMMU     1
1    VARUN     2
2  KARTHIK     3
3    AKHIL     4
4   VAMSHI     5
5  VIGNESH     6
6    VARMA     7
7   HARISH     8
8    GUNDU     9
9     BABU    10

In [128]:
MERGE_DATA1=pd.merge(DETAILS2 ,DETAILS1, on ='NAMES')
MERGE_DATA1

     NAMES  RANK       LOCATION  CODE
0     AMMU     1          UPPAL   123
1    VARUN     2       WARANGAL    34
2  KARTHIK     3       VR NAGAR    45
3    AKHIL     4       VS NAGAR    23
4   VAMSHI     5   VASAVI NAGAR     4
5  VIGNESH     6  PARGATI NAGAR    89
6    VARMA     7          SURAT    65
7   HARISH     8        JAGITAL   432
8    GUNDU     9     KARIMNAGAR   789
9     BABU    10         ONGOLE    64

In [129]:
merge_data2=pd.merge(MERGE_DATA1,roles_df, on ='NAMES')
merge_data2

     NAMES  RANK       LOCATION  CODE                      Role
0     AMMU     1          UPPAL   123                   Founder
1    VARUN     2       WARANGAL    34            Growth Manager
2  KARTHIK     3       VR NAGAR    45         Community Manager
3    AKHIL     4       VS NAGAR    23         Community Manager
4   VAMSHI     5   VASAVI NAGAR     4           Course Designer
5  VIGNESH     6  PARGATI NAGAR    89           Course Designer
6    VARMA     7          SURAT    65  Public Relations Manager
7   HARISH     8        JAGITAL   432           Course Designer
8    GUNDU     9     KARIMNAGAR   789           Course Designer
9     BABU    10         ONGOLE    64  Public Relations Manager

In [132]:
newfile=pd.read_csv('sample_contacts.csv')

In [133]:
newfile.head(5)

   ID       Name               Role         Phone       City
0   1      Nihar            Founder  111-111-1111  Hyderabad
1   2    Vignesh     Growth Manager  222-222-2222    Chennai
2   3  Maheshwar  Community Manager  333-333-3333  Bangalore
3   4      Naman  Community Manager  444-444-4444      Delhi
4   5     Naveen  Community Manager  555-555-5555  Hyderabad

In [146]:
newfile.sort_values(by='Name')

   ID       Name               Role         Phone       City
2   3  Maheshwar  Community Manager  333-333-3333  Bangalore
3   4      Naman  Community Manager  444-444-4444      Delhi
4   5     Naveen  Community Manager  555-555-5555  Hyderabad
0   1      Nihar            Founder  111-111-1111  Hyderabad
5   6     Shreya    Course Designer  666-666-6666    Chennai
6   7     Varsha    Course Designer  777-777-7777     Mumbai
7   8      Varun         PR Manager  888-888-8888       Pune
1   2    Vignesh     Growth Manager  222-222-2222    Chennai

In [134]:
newfile.head(10)

   ID       Name               Role         Phone       City
0   1      Nihar            Founder  111-111-1111  Hyderabad
1   2    Vignesh     Growth Manager  222-222-2222    Chennai
2   3  Maheshwar  Community Manager  333-333-3333  Bangalore
3   4      Naman  Community Manager  444-444-4444      Delhi
4   5     Naveen  Community Manager  555-555-5555  Hyderabad
5   6     Shreya    Course Designer  666-666-6666    Chennai
6   7     Varsha    Course Designer  777-777-7777     Mumbai
7   8      Varun         PR Manager  888-888-8888       Pune

In [147]:
newfile.sort_values(by='City')

   ID       Name               Role         Phone       City
2   3  Maheshwar  Community Manager  333-333-3333  Bangalore
1   2    Vignesh     Growth Manager  222-222-2222    Chennai
5   6     Shreya    Course Designer  666-666-6666    Chennai
3   4      Naman  Community Manager  444-444-4444      Delhi
0   1      Nihar            Founder  111-111-1111  Hyderabad
4   5     Naveen  Community Manager  555-555-5555  Hyderabad
6   7     Varsha    Course Designer  777-777-7777     Mumbai
7   8      Varun         PR Manager  888-888-8888       Pune

In [148]:
newfile.sort_values(by='ID')

   ID       Name               Role         Phone       City
0   1      Nihar            Founder  111-111-1111  Hyderabad
1   2    Vignesh     Growth Manager  222-222-2222    Chennai
2   3  Maheshwar  Community Manager  333-333-3333  Bangalore
3   4      Naman  Community Manager  444-444-4444      Delhi
4   5     Naveen  Community Manager  555-555-5555  Hyderabad
5   6     Shreya    Course Designer  666-666-6666    Chennai
6   7     Varsha    Course Designer  777-777-7777     Mumbai
7   8      Varun         PR Manager  888-888-8888       Pune

In [149]:
newfile.sort_values(by='Role')

   ID       Name               Role         Phone       City
2   3  Maheshwar  Community Manager  333-333-3333  Bangalore
3   4      Naman  Community Manager  444-444-4444      Delhi
4   5     Naveen  Community Manager  555-555-5555  Hyderabad
5   6     Shreya    Course Designer  666-666-6666    Chennai
6   7     Varsha    Course Designer  777-777-7777     Mumbai
0   1      Nihar            Founder  111-111-1111  Hyderabad
1   2    Vignesh     Growth Manager  222-222-2222    Chennai
7   8      Varun         PR Manager  888-888-8888       Pune

In [135]:
newfile.tail()

   ID    Name               Role         Phone       City
3   4   Naman  Community Manager  444-444-4444      Delhi
4   5  Naveen  Community Manager  555-555-5555  Hyderabad
5   6  Shreya    Course Designer  666-666-6666    Chennai
6   7  Varsha    Course Designer  777-777-7777     Mumbai
7   8   Varun         PR Manager  888-888-8888       Pune

In [136]:
newfile.tail(5)

   ID    Name               Role         Phone       City
3   4   Naman  Community Manager  444-444-4444      Delhi
4   5  Naveen  Community Manager  555-555-5555  Hyderabad
5   6  Shreya    Course Designer  666-666-6666    Chennai
6   7  Varsha    Course Designer  777-777-7777     Mumbai
7   8   Varun         PR Manager  888-888-8888       Pune

In [137]:
newfile[::-1]

   ID       Name               Role         Phone       City
7   8      Varun         PR Manager  888-888-8888       Pune
6   7     Varsha    Course Designer  777-777-7777     Mumbai
5   6     Shreya    Course Designer  666-666-6666    Chennai
4   5     Naveen  Community Manager  555-555-5555  Hyderabad
3   4      Naman  Community Manager  444-444-4444      Delhi
2   3  Maheshwar  Community Manager  333-333-3333  Bangalore
1   2    Vignesh     Growth Manager  222-222-2222    Chennai
0   1      Nihar            Founder  111-111-1111  Hyderabad

In [139]:
newfile.columns

Index(['ID', 'Name', 'Role', 'Phone', 'City'], dtype='object')

In [141]:
newfile.dtypes

ID        int64
Name     object
Role     object
Phone    object
City     object
dtype: object

In [142]:
newfile.describe()

            ID
count  8.00000
mean   4.50000
std    2.44949
min    1.00000
25%    2.75000
50%    4.50000
75%    6.25000
max    8.00000

In [143]:
newfile.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      8 non-null      int64
 1   Name    8 non-null      object
 2   Role    8 non-null      object
 3   Phone   8 non-null      object
 4   City    8 non-null      object
dtypes: int64(1), object(4)
memory usage: 452.0+ bytes

In [144]:
s=pd.Series([5,8,"ammu",6])
s

0       5
1       8
2    ammu
3       6
dtype: object

In [150]:
s.describe()

count     4
unique    4
top       5
freq      1
dtype: int64

In [151]:
s.info()

<class 'pandas.core.series.Series'>
RangeIndex: 4 entries, 0 to 3
Series name: None
Non-Null Count  Dtype
--------------  -----
4 non-null      object
dtypes: object(1)
memory usage: 164.0+ bytes

In [7]:
import pandas as pd

In [8]:
df=pd.DataFrame({
    "NAME":["VAMSHII","RITHU","KRISHNA","SHIVA","JANU"],
    "YEAR":[2006,2008,2005,2007,2004]})
df

      NAME  YEAR
0  VAMSHII  2006
1    RITHU  2008
2  KRISHNA  2005
3    SHIVA  2007
4     JANU  2004

In [10]:
tittle=df.loc[2:,"YEAR"]
tittle

2    2005
3    2007
4    2004
Name: YEAR, dtype: int64

In [11]:
tittle=df.loc[2,"YEAR"]
tittle

np.int64(2005)

In [13]:
tittle=df.loc[2:5,"YEAR"]
tittle

2    2005
3    2007
4    2004
Name: YEAR, dtype: int64